### ISSUE TITLE
MmoItems support

### ISSUE THREAD

**Issue by dinobossytnew** [TechnicallyCoded/Inventory-Rollback-Plus#1]
could you add nbt mmoitems, and as many data as you can?

**Comment by TechnicallyCoded** [comment]
Hey sorry for taking so long to answer.

I did take a look at your request multiple time, looked through a bit of mmoitems documentation but didn't find any clear indication as to what needs to be added or why it wouldn't work.

Would it be possible for you to provide the nbt of a normal item that you know work ok and the nbt of an item that doesn't and ill see if I can add that. :)

**Comment by TechnicallyCoded** [comment]
Due to the lack of response I will close this feature request.
