### ISSUE TITLE
No Restore Inventory Button Found

### ISSUE THREAD

**Issue by ScottGarryFoster** [TechnicallyCoded/Inventory-Rollback-Plus#10]
Installing version V1.6.0
Using command:
/irp restore [player]

The button for restore the player's inventory doesn't show up.
**Is something missing regarding the install instructions?**

Full list of plugins installed:
![image](https://user-images.githubusercontent.com/44545313/113409257-d149de00-93a8-11eb-9a98-56c662098e71.png)

I'm OP on the server and tried on an account that was just admin with permission inventoryrollbackplus.* but not the one without plus and no button:
![image](https://user-images.githubusercontent.com/44545313/113409400-1b32c400-93a9-11eb-8f2d-345d5cac69c0.png)

**Comment by Romvnly-Gaming** [comment]
config.yml

## CAUTION - USE AT OWN RISK
## Enabling this option will show a button to restore a player's backup fully to their character when online.
## This will overwrite their current inventory completely and wipe what they currently have without backing it up first.
restore-to-player-button: true

**Comment by ScottGarryFoster** [comment]
Awesome thank you.

We'll be educating our staff on this so should be good.
