### ISSUE TITLE
Rerolls not showing

### ISSUE THREAD

**Issue by ETG-Jynx** [TechnicallyCoded/Inventory-Rollback-Plus#100]
I have InventoryRollbackPlus-1.6.7_1.jar and whenever someone dies its doesn't show there previous stuff and all that. In this photo the user has died many times yet its not showing and/or working.
INFO
-server is 1.18.2
![Desktop Screenshot 2022 08 06 - 01 39 06 10](https://user-images.githubusercontent.com/69044720/183112280-45e96306-4da7-4776-ada8-cdd62911b947.png)

**Comment by TechnicallyCoded** [comment]
Do they have the permission required to save their inventory on death?

**Comment by ETG-Jynx** [comment]
> Do they have the permission required to save their inventory on death?

Nope, how do I do that?

**Comment by TechnicallyCoded** [comment]
There is a list of permissions on the spigot plugin page.

**Comment by ETG-Jynx** [comment]
> There is a list of permissions on the spigot plugin page.

I have looked through the page and it dosen't say?

**Comment by TechnicallyCoded** [comment]
![image](https://user-images.githubusercontent.com/29813490/183976456-b0977ef1-7c53-4de7-9bf3-be483db72c27.png)

idk seems pr obvious to me.....
