### ISSUE TITLE
Can we link with "ReviveMe" to fix the bug?

### ISSUE THREAD

**Issue by surfishs** [TechnicallyCoded/Inventory-Rollback-Plus#105]
ReviveMe：https://www.spigotmc.org/resources/%E2%9A%94%EF%B8%8F-reviveme-1-14-1-19-papi-support-hexcolor-no-dependencies%E2%AD%95.99030/
This plugin changes state to down when the player dies and has invincibility time.
However, irp doesn't seem to recognize death correctly and will assume the player is dead every time they are attacked and create a death record like crazy.
Even if the player is not really dead.

**Comment by TechnicallyCoded** [comment]
So this other plugin breaks death system and you come asking here for me to fix this plugin?
Additionally, their closed source plugin doesn't allow me to even see what would be breaking it.
The only thing I could do is add a backup event that the other devs could cancel... I couldn't fix it even if I wanted to.

**Comment by TechnicallyCoded** [comment]
Closed due to lack of reply
