### ISSUE TITLE
Support: Time zone GMT

### ISSUE THREAD

**Issue by ElTodoFull** [TechnicallyCoded/Inventory-Rollback-Plus#107]
Hello! I want to use the timezone "GMT-3" but it seems to be invalid.
I'm not sure if I got it wrong or the plugin doesn't support it yet.
`[Server thread/WARN]: [InventoryRollbackPlus] Time zone "GMT-3" in config.yml is invalid. Defaulting to "UTC"`

Thank you in advance!

**Comment by TechnicallyCoded** [comment]
Try UTC-3 ?
