### ISSUE TITLE
Feature Request: (add a short feature title here)

### ISSUE THREAD

**Issue by TypicalShavonne** [TechnicallyCoded/Inventory-Rollback-Plus#108]
### What is missing:
choose to do /ir restore directly with player uuid
./ir restore <UUID>
#### **Additional context:**
So it is easier to ir restore for offline players and geyser players who have an custom uuid

**Comment by TechnicallyCoded** [comment]
Already a feature..?

**Comment by TypicalShavonne** [comment]
it isnt yet
i tried a player(bedrock) named ABC
but it seems the plugin tried to search for that player using minecraft java uuid instead of the bedrock modified one.

**Comment by TypicalShavonne** [comment]
it says non existed player/ never joined

**Comment by TechnicallyCoded** [comment]
can you send me the command you are trying to run?

**Comment by TypicalShavonne** [comment]
> can you send me the command you are trying to run?

./ir restore playername
