### ISSUE TITLE
Bug report: Stacktrace

### ISSUE THREAD

**Issue by LcyDev** [TechnicallyCoded/Inventory-Rollback-Plus#113]
### Bug description:
*This stacktrace showed up after attempting a inventory rollback*

### Server details:
 - Server type & version: *(git-Purpur-1900 MC: 1.19.3)*
 - InventoryRollbackPlus version: *(v1.6.8)*

### How to reproduce:
*N/A*

### What was expected:
*N/A*

### Screenshots, logs & other:
https://paste.gg/p/ConaII_/7c35cda3f9c9444e80e54532de578264

#### **Additional info:**
*N/A*

**Comment by TechnicallyCoded** [comment]
Thanks for the report!

According to the error, the playername you had to provide must be unclaimed by any mojang account in order to fail in such a way.
Corrected for the edge-case nonetheless.
