### ISSUE TITLE
Feature Request: (add a short feature title here)

### ISSUE THREAD

**Issue by Ammutadori075** [TechnicallyCoded/Inventory-Rollback-Plus#114]
### What is missing:
Add armor saving and restore.

### Specific changes to make:
In addition to the inventory, integrate the possibility to save and restore full armor , elytra , shield

### This feature already exists here:
N/A

#### **Additional context:**
N/A

**Comment by TechnicallyCoded** [comment]
Already a thing

**Comment by Ammutadori075** [comment]
I dont understand, it's already in progress or it wont be added?
