### ISSUE TITLE
Bug report: [short issue title]

### ISSUE THREAD

**Issue by Abood8001** [TechnicallyCoded/Inventory-Rollback-Plus#115]
### Bug description:
*the plugin keeps crashing my server*

### Server details:
 - Server type & version: *(paper 1.18.2)*
 - InventoryRollbackPlus version: *(1.5.4)*

### How to reproduce:
*Steps to reproduce the behavior. If not applicable just replace this line with N/A*

### What was expected:

(https://pastebin.pl/view/cfb6f169) this is the errors from the logs

#### **Additional info:**
*Add any other context about the problem here. If not applicable just replace this line with N/A*

**Comment by TechnicallyCoded** [comment]
This has something to do with your filesystem. The logs clearly show that I using a default configuration loading tool that's used by all plugins (or 99%). I have no control over how it does stuff and I don't even think it's paper, spigot, or bukkit's fault.
