### ISSUE TITLE
Bug report: Lag on join

### ISSUE THREAD

**Issue by HealingHalo8** [TechnicallyCoded/Inventory-Rollback-Plus#119]
I found a major bug with this plugin when writing to the data base, on join of any player the server will legitimentaly kill itself. 

InventoryRollbackPlus::Event: m.d.i.l.EventLogs (PlayerJoinEvent)count(20)  total(21.74% 48.517s, 47.45% of tick)avg(2,425.85ms per - 23.72ms/0.01 per tick)

Please help me resolve this issue, it drops the tps down to like 10 for like 2-10seconds on any player join!

https://timings.aikar.co/dev/?id=f1b2f6ee0fa0400da5d8072117b81cea

**Comment by TechnicallyCoded** [comment]
Aikar timings don't show anything useful other than your are having lag.

Use the spark profiler and send that here. Also, I have used my own plugin on servers for years and every time someone says "look IRP is lagging the server", I find and correct the real issue and they look really smart :/
So don't get ahead of yourself with the blame game

**Comment by TechnicallyCoded** [comment]
Closed due to lack of reply
