### ISSUE TITLE
Support: Using IRP Api

### ISSUE THREAD

**Issue by timjuic** [TechnicallyCoded/Inventory-Rollback-Plus#120]
Hi, is there a way to use IRP API to programmatically rollback users when needed? For example I would need to rollback a user  to his last world change backup, when an event in my plugin happens.

**Comment by TechnicallyCoded** [comment]
Technically, yes.. but it's not easily usable as "get the most recent backup" + "now apply that".

If you want to reverse engineer some of this, you can take a look at click listeners for the restore GUI and the restore commands for finding how the recent backups are found.
