### ISSUE TITLE
plugin save the players inventories when they disconnect? 

### ISSUE THREAD

**Issue by GkitArcher** [TechnicallyCoded/Inventory-Rollback-Plus#121]
Hi, this may be a question but it could be a bug, I am currently using version 1.6.8 of the plugin and I would like to know does the plugin save the players inventories when they disconnect? because it is already happening to me several times that they disconnect and reconnect and do not have their inventory items (it does not happen to everyone), but I am thinking that it could be that something is not saved correctly and when they enter again they have nothing... because it is not saved.

**Comment by TechnicallyCoded** [comment]
If they reconnect without items in their inventory, that's a server issue.. not this plugin. It can help you recover the lost inventories if this happens but it doesn't modify it unless you ask it to do so.

**Comment by t4ba** [comment]
im having the same kind thing not sure the issue with the plugin but i will test and let you know guys
