### ISSUE TITLE
Bug report: Plugin does not work on Purpur 1.19.4

### ISSUE THREAD

**Issue by ballincat45** [TechnicallyCoded/Inventory-Rollback-Plus#124]
### Bug description:
When entering the command "/ir restore namehere" it opens up the menu, but when you click on the icons it errors resulting in the inventory not being rolledback to it's original state.

### Server details:
 - Server type & version: Current: git-Purpur-1953 (MC: 1.19.4)*
 - InventoryRollbackPlus version: InventoryRollbackPlus v1.6.7

### How to reproduce:
1. Obtain a rollback or backup.
2. Enter the command "/ir restore namehere"
3. Click on one of the menu items, i.e. bone, tree, etc
4. Error occurs at this point
### What was expected:
I expected this plugin to rollback the inventory of a player on my test server, but it ended up doing nothing.
### Screenshots, logs & other:
https://pastebin.com/9xqdLHdE

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
I updated the plugin with additional debug features 

Please download the beta from here
https://my.gcnt.net/plugins/InventoryRollbackPlus/download/SNAPSHOT-1.6.10_2

Replace your existing IRP jar with the one above
Add a line in your IRP config with exactly this: `debug: true`
Reboot the server

Then send your entire log file

**Comment by TechnicallyCoded** [comment]
Stale
