### ISSUE TITLE
Shulker Box Duplication

### ISSUE THREAD

**Issue by neeeekolaz** [TechnicallyCoded/Inventory-Rollback-Plus#127]
Hello, apologies if this is the wrong place for this.

I installed this plugin recently (1.19.4) and I've got a single player that has a shulker box duplicating in their enderchest. Unfortunately we also think that it is replacing an inventory slot in their inventory, effectively deleting items.

Has anyone experienced this before? I've got the below plugins, maybe there's some kind of conflict?
Bluemap, ChestSort, EditableSigns, InfoHUD, InventoryRollbackPlus, ItemSwapper, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, SDLink, ServerBackup, WorldEdit, XpBottler.

Let me know if you need anymore info.

**Comment by TechnicallyCoded** [comment]
IRP does not edit inventories unless you click a button after turning on the option in the config and having the staff permission to make it do so

**Comment by TechnicallyCoded** [comment]
The chances that this is caused by IRP is basically 0.0000001%
