### ISSUE TITLE
Optional Backups Toggle

### ISSUE THREAD

**Issue by w41k3r26** [TechnicallyCoded/Inventory-Rollback-Plus#13]
Absolutely a life-saving plugin but recently been eating a lot of CPU. The ability to toggle listening to certain events would make it much better so that I can only have it save items on deaths.

So for example in config and option to turn of each inventory backup type such as world changes and joins/quits.

![image](https://user-images.githubusercontent.com/64218536/115676648-6c612280-a36d-11eb-9446-1d79836c0819.png)

**Comment by TechnicallyCoded** [comment]
This can already done with the permissions listed on the plugin page.
If you deny the specific permission to a player, the saves will never be created for that player.

[](https://www.spigotmc.org/resources/85811/)

**Comment by TechnicallyCoded** [comment]
Will be closed in a few days unless a response is given.

**Comment by w41k3r26** [comment]
Thank you.
