### ISSUE TITLE
Bug report: [Incorrect chat info on xp restore]

### ISSUE THREAD

**Issue by InnerAbyssal** [TechnicallyCoded/Inventory-Rollback-Plus#133]
### Bug description:
*When restoring player xp the chat msg the player receives says the incorrect xp level information*

### Server details:
- ![image](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/assets/126091009/78353830-07bf-46c6-9d1c-06e7c82fb06a)
- ![image](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/assets/126091009/2474052f-7917-49aa-b62c-d22028c79b9b)

### How to reproduce:
- Have a player die with a few levels of experience.
- irp restore player
- navigate to their most recent death inventory in the GUI
- use "Restore Player XP" option
- the player will receive a message that displays an inaccurate/incorrect xp level that was restored to them.

### What was expected:
- That the chat message information matches the actual xp level

### Screenshots, logs & other:
https://youtu.be/mpUf-fAj3h8

**Comment by TechnicallyCoded** [comment]
Nice catch, I don't know how a never noticed this 😅
