### ISSUE TITLE
Feature Request: Support for InventoryPages

### ISSUE THREAD

**Issue by dudefoxlive** [TechnicallyCoded/Inventory-Rollback-Plus#135]
Recently started using a plugin called InventoryPages. It works great but when you die as expected Inventory Rollback Plus doesn't see the other pages. Would there by any possibly that this could be added? [Link to plugin](https://www.spigotmc.org/resources/inventorypages.110043/)

**Comment by TechnicallyCoded** [comment]
They don't have a GitHub so my answer is required to be no, sorry. I cannot add support for anything without being able to see how it works.
Secondly, I assume that this system works by switching out your inventory items while in-game. This effectively means that your inventory is not extended but, instead, handled by another plugin's storage. It would require modifying another plugin's data... and especially without an official API, that's a huge no no.
