### ISSUE TITLE
Support: Single click restore

### ISSUE THREAD

**Issue by realbaku** [TechnicallyCoded/Inventory-Rollback-Plus#136]
I enabled the "Single click restore" function but when i save the config.yml file and reload the plugin, it is still disabled. I can't restore the players inventory.

**Comment by TechnicallyCoded** [comment]
What happens if you restart the server?

**Comment by TechnicallyCoded** [comment]
If it still doesn't work, please provide full server logs 
and /version
and /about InventoryRollbackPlus
use something like pastebin to send the results.

**Comment by realbaku** [comment]
https://pastebin.com/raw/eXxnABcF

**Comment by realbaku** [comment]
https://postimg.cc/7GKTTMP6

**Comment by TechnicallyCoded** [comment]
This is after a full server reboot?

**Comment by realbaku** [comment]
yes

**Comment by realbaku** [comment]
It is working!

**Comment by TechnicallyCoded** [comment]
Great!
