### ISSUE TITLE
Single click restore isnt working

### ISSUE THREAD

**Issue by lengamer09** [TechnicallyCoded/Inventory-Rollback-Plus#139]
When i try to use inventoryrollbackplus it says "Single Click restore is disabled in the config.yml file!" 
but I dont see anything about it in the file.

**Comment by TechnicallyCoded** [comment]
https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/blob/94775f422b904af19efc50be9a58c3c01f6acb3e/src/main/resources/config.yml#L53

**Comment by TechnicallyCoded** [comment]
Inactive
