### ISSUE TITLE
Bug report: Incompatible with AngelChest

### ISSUE THREAD

**Issue by ClayCoffee** [TechnicallyCoded/Inventory-Rollback-Plus#145]
### Bug description:
*A clear and concise description of what the bug is.*
When AngelChest is installed, the items backed up after a player's death are empty.

### Server details:
 - Server type & version: *Current: git-Purpur-"4f43c72" (MC: 1.20.2)**
 - InventoryRollbackPlus version: *Running InventoryRollbackPlus v1.6.14*
 

### How to reproduce:
1. Install AngelChest
2. Die
3. The items backed up are empty.

### What was expected:
*A clear description of what you expected to happen. If not applicable just replace this line with N/A*
N/A

### Screenshots, logs & other:
*If applicable, add screenshots, logs, /timings links, /spark profiler links here.
If your logs are longer than 30 lines provide a link to a paste (https://pastebin.com) to keep the issue readable.*
```
If it's no more than 30 lines you can just put the log in here. Otherwise, you can delete this code block.
```

#### **Additional info:**
*Add any other context about the problem here. If not applicable just replace this line with N/A*
https://www.spigotmc.org/resources/angelchest-free.60383/

**Comment by TechnicallyCoded** [comment]
This was already answered in the discord server. Some plugins wipe your inventory instead of just not dropping items. There is nothing I can do to prevent this. Switch plugins. 

https://discord.com/channels/557199869870211132/1159115177166372864
