### ISSUE TITLE
Bug report: Conflicts with Angel Chest

### ISSUE THREAD

**Issue by LKits** [TechnicallyCoded/Inventory-Rollback-Plus#146]
### Bug description:
Doesn't save inventory with AngelChest plugin. Maybe AngelChest cancels the event or something.
https://www.spigotmc.org/resources/angelchest-free.60383/

### Server details:
 - Server type & version: Paper 1.20.2
 - InventoryRollbackPlus version: 1.6.14

### How to reproduce:
Die as a player, Angel Chest appears and IRP doesn't save death inventory.

### What was expected:
*A clear description of what you expected to happen. If not applicable just replace this line with N/A*

### Screenshots, logs & other:
*If applicable, add screenshots, logs, /timings links, /spark profiler links here.
If your logs are longer than 30 lines provide a link to a paste (https://pastebin.com) to keep the issue readable.*
```
If it's no more than 30 lines you can just put the log in here. Otherwise, you can delete this code block.
```

#### **Additional info:**
*Add any other context about the problem here. If not applicable just replace this line with N/A*

**Comment by TechnicallyCoded** [comment]
Incompatible plugin. It clears all items from a player's inventory instead of cancelling the drops.

https://discord.com/channels/557199869870211132/1159115177166372864

**Comment by mfnalex** [comment]
Set `dont-clear-inventory` to `true` in AngelChest's config.yml (line 648 in the default config.yml as of version 10.0.0)

**Comment by LKits** [comment]
Hey! Can't see it in config.yml
https://github.com/JEFF-Media-GbR/Configs/blob/main/Configuration%20Files/AngelChest/config.yml

**Comment by mfnalex** [comment]
That repository is outdated. Just update to AngelChest 10.0.0 and the option will be in your config in the section „Other plugins“
