### ISSUE TITLE
Gui not working

### ISSUE THREAD

**Issue by obbutt** [TechnicallyCoded/Inventory-Rollback-Plus#149]
### Bug description:
Clicking anything in the gui has no response 

### Server details:
 This server is running Paper version git-Paper-"62b220a" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 62b220a)
You are running the latest version
Previous version: git-Paper-"850b736" (MC: 1.20.4)
 v1.6.7

### How to reproduce:
Just open any gui click anything and there is nothing

### What was expected:
I was expecting for the inventory backups to be shown but there is no way to access it

**Comment by TechnicallyCoded** [comment]
Failed to produce logs of the server as requested.

Also, you are 7 versions out of date according to 1.6.7.
