### ISSUE TITLE
Player backups are not saved.

### ISSUE THREAD

**Issue by Savranchuk** [TechnicallyCoded/Inventory-Rollback-Plus#151]
![Безымянный](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/assets/130406584/48083f65-8594-440d-8c5b-056394de51d3)

Some players make backups, and some don't. The plugin randomly selects who should make the backup.

**Comment by TechnicallyCoded** [comment]
Probably based on your permissions. Please check that everyone has the permissions or backups. These are listed on the spigot plugin page.

**Comment by TechnicallyCoded** [comment]
Closed due to inactivity
