### ISSUE TITLE
Prefix changes

### ISSUE THREAD

**Issue by ShadoW4719** [TechnicallyCoded/Inventory-Rollback-Plus#16]
It was already mentioned on the Spigot page but just to be sure it goes through and you don't forget it, imma send it here also!

Could you make it so we can edit the prefix, or completely remove it? The current one just doesn't fit at all with my server theme.
Also, EST time isnt working properly. Is there a work around?

**Comment by ShadoW4719** [comment]
I see there has been changes made but what I was refering to was actually the In-Game prefix, not the MySQL database prefix.
The current one is "[InventoryRollbackPlus]" and I would like to change it to fit my server chat theme.

**Comment by TechnicallyCoded** [comment]
Hey sorry for the misunderstanding, the contributor referenced this issue when creating the pull request, I just added the tag as resolved in an autopilot way 😅. Thanks for pointing that out.

**Comment by TechnicallyCoded** [comment]
Hey I am looking at adding support for this soon. 

I can think of a few things that could possibly not fit in a themed server:
- Are chat colors are issue?
- Are the type of brackets used an issue?
- Should there be a way to select a shortened version of the plugin name? (like change InventoryRollbackPlus to IRP

Let me know ^^

**Comment by ShadoW4719** [comment]
Basically all I'm really looking for is to customize the prefix's name.
In my case, I would probably change it to "&c&lRollback &8▪︎ " or something!
But another player could use for example "InvRollback" or whatever.

Pretty much all spigot plugin as this feature implemented.

**Comment by JakeyPrime** [comment]
Made a proper issue for this in #31 so may we will get it eventually.
It's such an eyesore.

**Comment by NickPlayzMC** [comment]
Please add this... it'd be very useful.

**Comment by JakeyPrime** [comment]
> Please add this... it'd be very useful.

It's in the dev branch, but who knows when that will be live, compiled it myself and it works great. Hopefully in the public version soon!

**Comment by TechnicallyCoded** [comment]
> 
> 
> > Please add this... it'd be very useful.
> 
> It's in the dev branch, but who knows when that will be live, compiled it myself and it works great. Hopefully in the public version soon!

That's what I am trying to make sure of.. working great for multiple people. That does mean that I have to distribute these beta versions to friends and wait to see if anything happens that I didn't expect. I am very glad that you haven't found any major issues with it so far :)

**Comment by TechnicallyCoded** [comment]
An update was pushed that adds this feature!
Thanks for your suggestion!

(issue will be closed soon)
