### ISSUE TITLE
The ability to take items from the rollback

### ISSUE THREAD

**Issue by DisGanTe** [TechnicallyCoded/Inventory-Rollback-Plus#160]
### Bug description:
Players (helpers) who have access to the inventory rollback can take items from it, and it is more difficult to detect this than if the helper abused the rollbacks, endlessly rolling back his inventory. Is it possible to somehow prohibit taking these resources directly from the rollback menu?

### Server details:
Ver 1.16.5 
Java 16 
Purpur

**Comment by TechnicallyCoded** [comment]
This has already been solved with permissions. Please take another look at the spigot description page.
