### ISSUE TITLE
Error on gui click on 1.21.1

### ISSUE THREAD

**Issue by Portal2001** [TechnicallyCoded/Inventory-Rollback-Plus#165]
### Bug description:
cant click gui to open backup pages like death

### Server details:
 - Server type & version: *1.21.1*
 - InventoryRollbackPlus version: *1.6.17*

### How to reproduce:
*open GUI and click any backup section*

### What was expected:
*to open backup list in a gui*

### Screenshots, logs & other:
log:  https://mclo.gs/BYdhbIS

**Comment by TechnicallyCoded** [comment]
Fixed in b5019c175b1264a38a6a759836b048fb985db804
