### ISSUE TITLE
Bug report: [CombatLogX and FactionsKore bosses ]

### ISSUE THREAD

**Issue by TwitterTOS** [TechnicallyCoded/Inventory-Rollback-Plus#167]
### Bug description:
*when the player logs mid combat their inventory isn't being saved to inventory roll back 

2. When players die to Faction Kores bosses abilities those inventories aren't being saved either

### Server details:
 - Server type & version: *(paste the output of /version here)*
Sorry filling this on my phone but it's a 1.8 server using wine spigot

**Comment by TechnicallyCoded** [comment]
Please provide the required information requested for bug reports. It is impossible to do anything with the information provided.
