### ISSUE TITLE
Permission issues with inventory saves

### ISSUE THREAD

**Issue by dont-be-nothing** [TechnicallyCoded/Inventory-Rollback-Plus#168]
### Doesn't save the player inventory
so the thing is i installed plugin and ran it. it doesn't the player inventory but it does on enderchest. no errors showing on the console.
also i tried newer/older version to see if it's the case but it wasn't.
paper 1.20.4

**Comment by dont-be-nothing** [comment]
ok so it worked but doesn't work if you are op

**Comment by TechnicallyCoded** [comment]
Given your description, you need to look into updating the permissions for your users/groups. As a result of the lack of logs and other critical information requested, I am unable to help you any further.

**Comment by dont-be-nothing** [comment]
another problem, it doesn't work with geyser mc.
bedrock players inventories will not be saved

**Comment by TechnicallyCoded** [comment]
All players are java players, no matter how they connect. Geyser pretends to have java players joining. There is no difference once the plugins need to handle the plugins. Only specific plugins that manually handle packets, especially receiving them will see a difference. IRP has no packet handling whatsoever. Still no logs were provided. I will therefore close this issue, I unfortunately can't do anything without the information requested.
