### ISSUE TITLE
Bug report: Player-executed commands not working

### ISSUE THREAD

**Issue by Onatparagus** [TechnicallyCoded/Inventory-Rollback-Plus#169]
### Server details:
 - Server version: Paper version 1.21.1-61-master@10f5879
 - IRP Version: v1.6.18
 
### Bug description:
When my server was on 1.20.4, the plugin worked fine (v1.6.14). I've updated all my plugins including IRP, and upgraded the server to 1.21.1 (via Exaroton). Now, no matter what I do, none of the commands entered in chat do anything, not even showing any error message in chat or console. I am op and have the required permissions. If I enter the commands through console, it works as intended.

### How to reproduce:
Simply opening up the server with the version and plugins given in the log below and attempting to execute any IRP command.

### Logs, screenshots & other:
https://mclo.gs/K914Mdc

PS: Sorry if there's any problem, first time opening an issue.

**Comment by Onatparagus** [comment]
UPDATE: Issue is resolved, turns out it was PerWorldPlugins causing this problem in 1.21.1.

**Comment by TechnicallyCoded** [comment]
Glad you figured this out. For future reference you did great for all the required info, helps a lot :)
