### ISSUE TITLE
Feature Request: (Dying to FactionKore's bosses saving inventory in "death")

### ISSUE THREAD

**Issue by TwitterTOS** [TechnicallyCoded/Inventory-Rollback-Plus#170]
### What is missing:
*When you die to the bosses abilities your inventory isn't saved in "death", I would like that to be added*

### Specific changes to make:
*You just need to listen to the PlayerDeathEvent, and check if the player died to bosses ability, if so save the inventory to "death"
Factions Kore (Bosses) -> https://discord.gg/x5MG6FHkzf
*

### This feature already exists here:
*N/A*

#### **Additional context:**
*N/A*

**Comment by TechnicallyCoded** [comment]
The plugin already listens to the PlayerDeathEvent. Please re-open a new issue with more specific information.
