### ISSUE TITLE
Bug report: [Massive error in console]

### ISSUE THREAD

**Issue by EurusTheGreat** [TechnicallyCoded/Inventory-Rollback-Plus#173]
### Server details:
 - Server version: 1.21.1-2328-d49ca07 (MC: 1.21.1)
 - IRP Version: InventoryRollbackPlus version 1.6.19

### Bug description:
- Whenever I type the command `/ir restore [Name]` it opens the GUI normally but all buttons cease to function.

### How to reproduce:
- By simply typing the `/ir restore` command.

### Logs, screenshots & other:
- [https://pastebin.com/YtyfCr71](https://pastebin.com/YtyfCr71)

#### **Additional info:**
- This only happens on this version of IRP, but on 1.6.18 it works perfectly fine.

**Comment by TechnicallyCoded** [comment]
Hey, sorry for the delay due to uni work, will get to this asap.
