### ISSUE TITLE
Bug report: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()

### ISSUE THREAD

**Issue by servicomcr** [TechnicallyCoded/Inventory-Rollback-Plus#174]
/irp restore carlosprro

LOG
https://pastebin.com/7eeeBUBR

**Comment by TechnicallyCoded** [comment]
Hey, will take a look at this asap. Sorry for the wait.

**Comment by servicomcr** [comment]
Hello, thank you, please I can't restore inventories since the last update,
