### ISSUE TITLE
Bug report: Max data size of mysql column exceeded when saving long books (or anything with a lot of data)

### ISSUE THREAD

**Issue by Loving11ish** [TechnicallyCoded/Inventory-Rollback-Plus#18]
### Bug description:
An error saving players enderchests when using MySQL if the player has a custom written book within their echest.

### Server details:
 - Server type & version: `This server is running Paper version git-Paper-592 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
08.05 08:50:02 [Server] INFO You are 59 version(s) behind`
 - InventoryRollbackPlus version: `Running InventoryRollbackPlus v1.6.0
08.05 08:49:26 [Server] INFO Authors:
08.05 08:49:26 [Server] INFO - Maintained/updated by: TechnicallyCoded
08.05 08:49:26 [Server] INFO - Original author: danjono
08.05 08:49:26 [Server] INFO Update link:
08.05 08:49:26 [Server] INFO https://www.spigotmc.org/resources/inventoryrollback-plus.85811/`

### How to reproduce:
The server has to have the 'VanillaTweaks Armourstand Statues book' data pack and this book must be placed within an echest.  The plugin must be set to save to an external MySQL database.  The error then occurs anytime a save is to take place.

### What was expected:
N/A

### Screenshots, logs & other:
`[Server] WARN com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'ender_chest' at row 1
08.05 08:45:23 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
08.05 08:45:23 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
08.05 08:45:23 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
08.05 08:45:23 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
08.05 08:45:23 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
08.05 08:45:23 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
08.05 08:45:23 [Server] WARN at me.danjono.inventoryrollback.data.MySQL.saveData(MySQL.java:425)
08.05 08:45:23 [Server] WARN at me.danjono.inventoryrollback.data.PlayerData.lambda$saveData$0(PlayerData.java:407)
08.05 08:45:23 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
08.05 08:45:23 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
08.05 08:45:23 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
08.05 08:45:23 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
08.05 08:45:23 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
08.05 08:45:23 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)
08.05 08:45:24 [Server] WARN com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'ender_chest' at row 1
08.05 08:45:24 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
08.05 08:45:24 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
08.05 08:45:24 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
08.05 08:45:24 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
08.05 08:45:24 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
08.05 08:45:24 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
08.05 08:45:24 [Server] WARN at me.danjono.inventoryrollback.data.MySQL.saveData(MySQL.java:425)
08.05 08:45:24 [Server] WARN at me.danjono.inventoryrollback.data.PlayerData.lambda$saveData$0(PlayerData.java:407)
08.05 08:45:24 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
08.05 08:45:24 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
08.05 08:45:24 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
08.05 08:45:24 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
08.05 08:45:24 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
08.05 08:45:24 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)`

#### **Additional info:**
This is my IRP config file.
`enabled: true
max-saves:
  join: 10
  quit: 10
  death: 50
  world-change: 10
  force: 10
backup-lines-visible: 4
folder-location: DEFAULT
mysql:
  enabled: true
  details:
    host: 51.**.***.***
    port: 3306
    database: 'apexMC714396'
    username: 'MYUSERNAME'
    password: 'MYPASSWORD'
    use-SSL: false
    verifyCertificate: true
    allowPubKeyRetrieval: false
sounds:
  teleport:
    enabled: true
  inventory:
    enabled: true
  food:
    enabled: true
  hunger:
    enabled: true
  xp:
    enabled: true
time-zone: GMT
time-format: dd/MM/yyyy hh:mm:ss a z
restore-to-player-button: true
update-checker: true
bStats: true`

**Comment by TechnicallyCoded** [comment]
For people looking at these issues: this should be solved in upcoming releases
