### ISSUE TITLE
Bug report: [Plugin calculates player UUID by itself instead of trusting uuidcache]

### ISSUE THREAD

**Issue by GitGoppy** [TechnicallyCoded/Inventory-Rollback-Plus#22]
### Bug description:
I use plugin called Fastlogin, one of the settings of said plugin is to assign premium UUIDs to premium accounts, while giving cracked UUIDs to cracked accounts, Inventoryrollbackplus reads whether server is in online mode and based on that calculates a cracked UUID or asks mojang for real UUID.
Since the plugin saves premium uuids for premium players on a online-mode=false server, the history of said players can't be opened while they are offline because it tries to open a calculated cracked UUID when the actual data is saved under a premium UUID.

How to fix:
Instead of calculating UUIDs like this based on whether server has enabled online mode, you should trust uuid cache to give you the correct UUID for the player and then use that to open offline player inventory histories

**Comment by TechnicallyCoded** [comment]
This plugin is a fork of InventoryRollback, therefore I have not written the majority of the code. Please indicated which files & lines you are concerned about.

Also, I should add that a quick search for `getOnlineMode` has 0 occurrences in the entire project,

**Comment by TechnicallyCoded** [comment]
If no additional response is given, this issue will be closed in 7 days.

**Comment by TechnicallyCoded** [comment]
Closed due to inactivity.
