### ISSUE TITLE
Bug report: [spigot 1.17 use /ir restore player   crash]

### ISSUE THREAD

**Issue by tygh78071388** [TechnicallyCoded/Inventory-Rollback-Plus#23]
### Bug description:
use /ir restore player
server crash

### Server details:
 - Server type & version: *(paste the output of /version here)*
[22:24:25] [Server thread/INFO]: This server is running CraftBukkit version 3104-Spigot-a09c0bb-d747f8e (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[22:24:25] [Server thread/INFO]: Checking version, please wait...
[22:24:26] [Thread-16/INFO]: You are 27 version(s) behind
 - InventoryRollbackPlus version: *(copy the version from /irp version here)*
 Inventory Rollback Plus (1.8 - 1.17.x) 1.6.1

### How to reproduce:
/ir forcebackup all   (OK)

/ir restore tygh89071388  (crash)

### What was expected:
N/A

### Screenshots, logs & other:
[server.log](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/files/6644035/server.log)
[crash-2021-06-13_22.09.53-server.txt](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/files/6644036/crash-2021-06-13_22.09.53-server.txt)

PLS help me    THX ！

**Comment by tygh78071388** [comment]
Update spigot server..... problem solved
sorry   ...  XD

**Comment by TechnicallyCoded** [comment]
No worries, always willing to help even for simple mistakes ^^

**Comment by pasaperez** [comment]
I have the same problem, i don't know how to solve... my server crash every tima i use the /irp restore "player". Any help?

**Comment by TechnicallyCoded** [comment]
Please create a new issue. This is closed.
