### ISSUE TITLE
Record fake fall in worldguard regions with invincible flag

### ISSUE THREAD

**Issue by EpicPlayerA10** [TechnicallyCoded/Inventory-Rollback-Plus#24]
### Bug description:
Plugin is recording fake fall in worldguard regions with invincible flag

### Server details:
 - Server type & version: This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - InventoryRollbackPlus version: Running InventoryRollbackPlus v1.6.1
### How to reproduce:
 - Create a worldguard region
 - Add `invincible` flag to this region
 - Jump in the region from a height where you would die
 - And this fall is recorded as a death

### What was expected:
I expected that it wasn't recorded

### Screenshots, logs & other:
not relevant

**Comment by TechnicallyCoded** [comment]
Hey btw I am sorry for not responding quicker. I am in the middle of exams right now. Thanks for contributing your time though :)
