### ISSUE TITLE
how to close a save 

### ISSUE THREAD

**Issue by lidashuai-li** [TechnicallyCoded/Inventory-Rollback-Plus#29]
Hello, author, I would like to ask, if I want to close a save, I will set the maximum number to - 1 and 0 does not work. Is there any way to disable a save, or can I add one?

**Comment by TechnicallyCoded** [comment]
Remove the permission from the players using a plugin like luckperms. All permissions are listed on the spigot webpage.

**Comment by lidashuai-li** [comment]
Thank you very much for answering my stupid question. By the way, your plug-in is really easy to use. If only you could reduce the occupation
