### ISSUE TITLE
Feature Request: Customizable Prefix

### ISSUE THREAD

**Issue by JakeyPrime** [TechnicallyCoded/Inventory-Rollback-Plus#31]
### What is missing:
Being able to edit the messages file to customize the prefix. Even just the color.

### Specific changes to make:
A config option near the top of the configuration file to allow for coloring or customizing the prefix.

### This feature already exists here:
Almost every other plugin allows for coloring or customizing the prefix of messages.

#### **Additional context:**
N/A

**Comment by TechnicallyCoded** [comment]
Duplicate of #16
