### ISSUE TITLE
Support: No Overwrite Option

### ISSUE THREAD

**Issue by Majoramari** [TechnicallyCoded/Inventory-Rollback-Plus#32]
Hello, Why I don't have to overwrite option like this:
![image](https://user-images.githubusercontent.com/33487552/127407569-fe3c3fc4-ab6e-4d85-a036-71856962c2c0.png)

i have it like this:
![image](https://user-images.githubusercontent.com/33487552/127407551-ae2be479-5599-4a2c-b9bc-92c97d3cab7a.png)

**Comment by TechnicallyCoded** [comment]
Enable the option in the config.yml file

**Comment by Majoramari** [comment]
Okay i though the option should be named `Overwrite` but it's `restore-to-player-button`

i'm typing that just in case anyone needed it and thanks
