### ISSUE TITLE
Time zones? 

### ISSUE THREAD

**Issue by Deeptanil** [TechnicallyCoded/Inventory-Rollback-Plus#38]
What are the possibile time zones?
I need to change from GMT to IST.

Also do you have a discord support?

**Comment by TechnicallyCoded** [comment]
You could just use UTC+05:30 I think. However, I have never tried offsetting by minutes before so tell me if it works ^^

**Comment by Deeptanil** [comment]
That did not work! I tried doing that! It just shows in GMT or the plugin breaks.

**Comment by TechnicallyCoded** [comment]
Ok, ok, chill... I was just asking if that works. Now that you have confirmed that it does not, I will dig deeper into what the problem could be.

**Comment by TechnicallyCoded** [comment]
Also, there is this little issue with using IST
![image](https://user-images.githubusercontent.com/29813490/134004196-7b760758-9a77-4820-8c2d-4c8e6ab81c24.png)

**Comment by TechnicallyCoded** [comment]
Please try the latest update, I changed a few minor things related to timezones.
While testing, the timezone: IST worked. Tell me if that helps :)

**Comment by Deeptanil** [comment]
Nope still didn't work! time-zone: IST didn't work!
Also do you have any discord support?

**Comment by TechnicallyCoded** [comment]
I currently don't have a discord server that I use for issues but you could provide me with your discord tag and I don't mind adding you to get this sorted :)

**Comment by Deeptanil** [comment]
Deeptanil#9539

**Comment by TechnicallyCoded** [comment]
I added you earlier today

**Comment by Deeptanil** [comment]
Omg I'm so sorry! I might have ignored it by mistake! Can u add me again!! Thanks

**Comment by TechnicallyCoded** [comment]
Resolved in discord DMs. 

_For those who are curious: It seems as though a restart was not performed, and therefore some changes were not applying correctly._

**Comment by USBCharger** [comment]
I'm also having this same issue. Using time-zone: 'UTC-5', I restarted the server, nothing seems to fix it. Any ideas?

**Comment by SrBedrock** [comment]
> I'm also having this same issue. Using time-zone: 'UTC-5', I restarted the server, nothing seems to fix it. Any ideas?

```yml
## Set how the time is displayed on the backups.
time-zone: 'UTC-05:00'
```
