### ISSUE TITLE
Inventory wouldnt go after interact the GUI

### ISSUE THREAD

**Issue by jstan425** [TechnicallyCoded/Inventory-Rollback-Plus#4]
![image](https://user-images.githubusercontent.com/33200390/107119939-a457de00-68c5-11eb-8175-bcafd5190cc7.png)

There is a weird bug that after use the command the inventory will stay afloat in the screen forever.

**Comment by TechnicallyCoded** [comment]
Please try again using a vanilla installation of the game. That's a client side issue.
