### ISSUE TITLE
How to remove this message? (Admin Only Alert) 

### ISSUE THREAD

**Issue by MuruFuku** [TechnicallyCoded/Inventory-Rollback-Plus#42]
Every time I logged into our server, this message always pops up, is there a way to hide this message? It's kinda getting annoying and I wanna disable it. Hoping to hear from your response soon, thanks!

![image](https://user-images.githubusercontent.com/85186241/135666556-81f0f5f0-e3a7-461d-8704-b468966a4034.png)

**Comment by TechnicallyCoded** [comment]
Duplication of #40
