### ISSUE TITLE
Bug report: [After player die console spam warn]

### ISSUE THREAD

**Issue by DarrienNN** [TechnicallyCoded/Inventory-Rollback-Plus#43]
### Bug description:
*After adding kitpvp plugin, the plugin spam warning when someone die.*

### Server details:
 - Server type & version: *https://pastebin.com/DY3cHs0J*

 - InventoryRollbackPlus version: *https://pastebin.com/9x4MKVWW*

### How to reproduce:
*N/A*

### What was expected:
*Trying to make kitpvp + survival server 
https://www.spigotmc.org/resources/kitpvp-1-8-1-17-custom-kits-leaderboards-gui-levels-kill-streaks-abilities-more.27107/*

### Screenshots, logs & other:
```
https://pastebin.com/NN9UnMnJ
```

#### **Additional info:**
*N/A*

**Comment by TechnicallyCoded** [comment]
I don't see the file `1634125692249.yml`. Was it successfully deleted? Is it still showing the same errors?

**Comment by TechnicallyCoded** [comment]
I don't see the file in what you sent me..

**Comment by TechnicallyCoded** [comment]
Well that just disables the plugin in that world =P

**Comment by DarrienNN** [comment]
Yeah, maybe you can try yourself?

**Comment by TechnicallyCoded** [comment]
I don't have this issue myself. Make sure that file permissions are set correctly and you don't have any supplicates of the plugin installed at the same time.

**Comment by DarrienNN** [comment]
Yes all correctly

**Comment by TechnicallyCoded** [comment]
The patch to this issue should now be live on spigot ^^
