### ISSUE TITLE
Suggestion: Migration tool from Inventory Rollback to Inventory Rollback Plus

### ISSUE THREAD

**Issue by analogged** [TechnicallyCoded/Inventory-Rollback-Plus#46]
I've been using Inventory Rollback for a while and have tons of logs for it but would like to start using Inventory Rollback Plus instead. Currently with Inventory Rollback I have it saving all the information in the plugin folders but I can use MySQL or YAML.

Is there any way to get Inventory Rollback Plus to work with Inventory Rollback files? Or is there a way to migrate Inventory Rollback files to MySQL? 

I have thousands of players in my Inventory Rollback files so going through them one by one really isnt an option.

Hoping to have some solution to be able to switch / upgrade from Inventory Rollback to Inventory Rollback Plus without losing any of the data / rollbacks from the previous plugin that are not storred in MySQL.

**Comment by TechnicallyCoded** [comment]
Slight correction: it seems as though the original author had started a migration utility before ending the updates, I'll see if I consider that stable enough to ship along with a bug fix in the next day or two.

**Comment by analogged** [comment]
That's excellent thank you, I can wait no problem for the update. I'm upgrading because I like the new features of being able to roll back players inventory with one click as well as how it logs where projectiles come from. For the time being I'll just use Inventory Rollback so I'm not making rollback entries in both plugins and then once the update comes ill switch to Inventory Rollback Plus and migrate the dta all at once. Thanks so much!

**Comment by TechnicallyCoded** [comment]
The import tool is now available! You can get the update on spigot as usual ^^

Please backup your InvRollback & IRP data before attempting this. Let me know how it goes and if there is anything I could do to improve it :)
