### ISSUE TITLE
Bug report: 100 backups = LOTS of queries

### ISSUE THREAD

**Issue by Romvnly-Gaming** [TechnicallyCoded/Inventory-Rollback-Plus#47]
### Bug description:
When inventory plus is tasked with saving 100 backups, things start to get iffy. Even though it should be only querying one page worth of data, it's sky rocketing queries like no tomorrow

### Server details:
 - Server type & version: *(paste the output of /version here)*
 - InventoryRollbackPlus version: *(copy the version from /irp version here)*
Server type: Purpur, 1.17.1 latest build
IRP version: Latest
### How to reproduce:
*Steps to reproduce the behavior. If not applicable just replace this line with N/A*
Set your data saving solution to MySQL. Set your death backups to 100.
### What was expected:
Smooth usage, just handling one page at a time, not hundreds of queries being made.

### Screenshots, logs & other:
*If applicable, add screenshots, logs, /timings links, /spark profiler links here.
If your logs are longer than 30 lines provide a link to a paste (https://pastebin.com) to keep the issue readable.*
![msedge_zG3dHCQ5nX](https://user-images.githubusercontent.com/62443489/139001194-24283395-2ea5-452b-9069-5457802a4460.png)

https://user-images.githubusercontent.com/62443489/139001348-5e7f4fa7-fec6-4998-9826-157a0ba41982.mp4

the mouse is where I put started looking through pages...
#### **Additional info:**
N/A

**Comment by Romvnly-Gaming** [comment]
Sorry for the late response, I'll review the exact MySQL logs when tomorrow!

**Comment by TechnicallyCoded** [comment]
Could I get an update on this?

**Comment by TechnicallyCoded** [comment]
I will close this issue in a week if I can't get more information about this...
