### ISSUE TITLE
Feature Request: world whitelist for deaths and world switches

### ISSUE THREAD

**Issue by Romvnly-Gaming** [TechnicallyCoded/Inventory-Rollback-Plus#48]
### What is missing:
Whenever people die in our arena, they don't lose anything and it wastes our backup space. What I'd like is a world whitelist/blacklist for inventory backups for deaths and world switches, as nothing happens between when they switch worlds!

### Specific changes to make:
Add world whitelist/blacklist to prevent useless backups

### This feature already exists here:
N/A

#### **Additional context:**
N/A

**Comment by TechnicallyCoded** [comment]
Although this could be added, you can already achieve this by setting per-world permissions :)
