### ISSUE TITLE
High Resource Usage

### ISSUE THREAD

**Issue by Moosebobby** [TechnicallyCoded/Inventory-Rollback-Plus#49]
### Bug description:
High Resource usage from the plugin

### Server details:
 - Server type & version: Paper 1.16.4
 - InventoryRollbackPlus version: Latest (1.6.4)

### How to reproduce:
No Idea It just started recently

### What was expected:
The plugin to not use so many resources?

### Screenshots, logs & other:
https://gyazo.com/cbf7708129e02c29042fea74f9f197b8
There is nothing in logs about the lag

#### **Additional info:**
Not using MYSQL

**Comment by Moosebobby** [comment]
https://gyazo.com/700425e25ee2e28a30279622dada2c84

**Comment by TechnicallyCoded** [comment]
Thanks for the report I will take a look at that.

**Comment by TechnicallyCoded** [comment]
I can't help but notice that the API that is causing lag isn't used by the plugin..
Could you create a spark profiler please?

Step by step instructions in case you don't know what I am talking about:
Download the Spark plugin,
Install it on the server,
Restart the server,
Run /spark profiler
use the plugin for a bit
Run /spark profiler --stop
Copy the link it provides and send it to me here ^^

**Comment by Moosebobby** [comment]
https://spark.lucko.me/ZxZflwfJrg

I left it on for a bit longer cus i forgot to turn it off lol

**Comment by TechnicallyCoded** [comment]
When I search the spark logs there is literally nothing about the IRP plugin..... as if not even installed .... huh?

**Comment by TechnicallyCoded** [comment]
No reply for over a month and a half, assuming this is no longer an issue.
