### ISSUE TITLE
Crash on /ir restore player 1.17.1

### ISSUE THREAD

**Issue by ehetteNandaYo** [TechnicallyCoded/Inventory-Rollback-Plus#50]
### Bug description:
Crash on /ir restore player

### Server details:
 -  This server is running Purpur version git-Purpur-1400 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 144a08e on ver/1.17.1)
 - InventoryRollbackPlus version:  1.6.4 | Thursday at 4:16 PM

### How to reproduce:
Just /ir restore player maybe click the bone

### Screenshots, logs & other:
[*If applicable, add screenshots, logs, /timings links, /spark profiler links here.
If your logs are longer than 30 lines provide a link to a paste (https://pastebin.com) to keep the issue readable.*
```
If it's no more than 30 lines you can just put the log in here. Otherwise, you can delete this code block.

https://paste.gg/p/anonymous/7185939621b14318aae84f23699c527e/files/4767416f52034253922a1fb21d9da128/raw

**Comment by TechnicallyCoded** [comment]
Does this happen consistently (like every time you run the command)?

I myself use purpur to do tests before uploading updates and I haven't ever seen this. The problem I have with the logs provided is that they only reference mojang sections of code related to GameProfiles which could make sense as the plugin retrieves a player UUID when running the command but the inventoryrollbackplus plugin is not mentioned anywhere in the crash log.

**Comment by TechnicallyCoded** [comment]
Another thing I noticed is that you Purpur build is about a month out of date. Please update to a newer version as issues are possibly fixed from one day to another.

**Comment by TechnicallyCoded** [comment]
No further information, closing issue
