### ISSUE TITLE
Can't set time zone to EST

### ISSUE THREAD

**Issue by Wolfcoool** [TechnicallyCoded/Inventory-Rollback-Plus#56]
### Bug description:
When setting  EST, EDT, or ET under "time-zone" in config.yml,
I get this warning: [11:17:04 WARN]: [InventoryRollbackPlus] Time zone "EST" in config.yml is invalid. Defaulting to "UTC"
UTC-5 also does not work. 
### Server details:
 - Server type & version: *Paper version git-Paper-84 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: ae6fec6)*
 - InventoryRollbackPlus version: *(Running InventoryRollbackPlus v1.6.5)*
### What was expected:
Plugin to change time zone to EST

**Comment by TechnicallyCoded** [comment]
The built-in timezone handling from java is pretty bad. I have thought of re-writing this stuff manually to make it more reliable but haven't gotten around to it due to some limitations of doing so.

**Comment by TechnicallyCoded** [comment]
Just as a note: when I use this system it seems to work fine for me. This could indicate an issue with what java version you are using? I don't really know.

**Comment by Wolfcoool** [comment]
Setting EST works fine for you?
I'm on java 17, btw.

**Comment by TechnicallyCoded** [comment]
Ok, it seems that the settings actually applies correctly but still throws a error/ warning in the console. Have you checked the in-game menus for what time is listed?

**Comment by Wolfcoool** [comment]
(GitHub didn't notify me about your response, sorry)

Just checked and like you said, yes it does work but throws an error. 
Seems like you fixed it with that commit though, thank you!
