### ISSUE TITLE
Inventory cleared on reboot

### ISSUE THREAD

**Issue by TenReeez** [TechnicallyCoded/Inventory-Rollback-Plus#57]
### Bug description:
Random players are losing their inventories on logging out and coming back

### Server details:
1.18.1 R0.1-snapshot paper
1.6.5 inventory rollback plus

### How to reproduce:
N/A

### What was expected:
Since releasing a 1.18.1 server I have had random issues with players losing their inventories on logging out and coming back in.
I have had a Developer look at it. Made sure the UUID was correct etc. The players UUID has the items in it, but doesnt come through to game. It seems to be fixed when all plugins are removed, then uploaded it works for a while. But then after a while it happens to a random player(s) 
I have had my server host go through it. Not a node issue and cant see anything wrong

Inventoryrollback records what they logged out with, but on relog the join info is blank.

Both have suggested I contact plugin owners that have anything to do with invnetories.

### Screenshots, logs & other:
There is no console errors.

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
I would first take a look at logs, the inventory rollback has no permission to edit anyone's inventories. It retrieves it, copies it to a serialized format and that's the end of the story. 

However, IRP could help you find the real cause: check if the inventory is cleared when they leave. If it is cleared when leave then some plugin/or bug is clearing the inventory on player leave (check logs for errors at the time of cleared inv). If it's only when the player joins, check what plugins handle player join events (and logs for errors). 

I have a few suggestions as to what you could take a look at:
- (as stated previously, use IRP to check their inv as they left)
- check for plugins whoch have inventory "protection" features, such as login plugins keeping you from seeing an inventory without entering a password
- check for plugins which handle spawn-in events: such as essentials (that's a pr mature plugin though)
- do /plugins and send me the list of plugins for me to run an extra few check as to which ones touch player inventories

**Comment by TechnicallyCoded** [comment]
Any updates? I will close this in a few days if there is nothing left to answer.
