### ISSUE TITLE
MySQL not working

### ISSUE THREAD

**Issue by PRONIIX27** [TechnicallyCoded/Inventory-Rollback-Plus#62]
When I activate mysql and fill in all the fields for connect, an error appears in the console and the database does not work, it only happens with this plugin. I am using the latest version which is compatible with 1.18.

**Comment by TechnicallyCoded** [comment]
It is impossible for me to help you without additional information.

**Comment by PRONIIX27** [comment]
Yes, both things are done

**Comment by TechnicallyCoded** [comment]
Could you provide logs please.

**Comment by PRONIIX27** [comment]
ok this might help yo
![error](https://user-images.githubusercontent.com/65824129/149656005-53a716ac-ef32-4dfe-afd6-f809784c1e11.png)
u

**Comment by PRONIIX27** [comment]
![config](https://user-images.githubusercontent.com/65824129/149656198-b90bbc91-26d2-436f-b5b7-eeb33012c58d.png)

**Comment by TechnicallyCoded** [comment]
![image](https://user-images.githubusercontent.com/29813490/149662038-a5a50ddb-f704-4f28-987b-9245302f023f.png)

Please read the error, you are using SSL for a locahost database.

**Comment by TechnicallyCoded** [comment]
Additionally, when people ask for logs it's usually better to use paste services like pastebin or hastebin. People can't copy paste, search for, or easily read out of images. 

For search indexing purposes the error you have here is: java.sql.SQLNonTransientConnectionException: SSL Connection required, but not provided by server.

**Comment by PRONIIX27** [comment]
Thank you very much for the support, it works now, and sorry for the inconvenience and for my misinformation.
