### ISSUE TITLE
Bug report: Plugin disabling itself on restarts and stucks there.

### ISSUE THREAD

**Issue by NotSharwan** [TechnicallyCoded/Inventory-Rollback-Plus#64]
### Bug description:
*The inventoryrollbackplus plugin disables itself and becomes stuck whenever the server restarts. Even the console and memory usage are stuck, so if we clear the inventory data of players saved by this plugin, then only it works on the next restart. Otherwise, it gets stuck and disables on every restart.*

### Server details:
 - Server type & version: *Paper 1.18.1*
 - InventoryRollbackPlus version: *irp 1.6.5*

### How to reproduce:
*Happens every restart!*

### What was expected:
*It is expected to work without stuck and disabling.*

### Screenshots, logs & other:
*https://i.imgur.com/aer2r1G.png
https://mcpaste.io/56217a3969641bab*

#### **Additional info:**
*N/A*

**Comment by TechnicallyCoded** [comment]
What do you mean by a restart? Shutting the server down or reloading the plugin?
Have you tried removing the plugin temporarily and trying the same operation again?
You are mentioning a restart, what happens if you just run /stop?

**Comment by TechnicallyCoded** [comment]
Additional info: the plugin almost doesn't do anything on disable other than deleting a stored value in RAM in case you are doing /reload or using a plugin manager to reload the plugin. That's it, just preventing a possible error / memory leak.

**Comment by NotSharwan** [comment]
The console and memory usage are stuck after this line *[InventoryRollbackPlus] Disabling InventoryRollbackPlus v1.6.5*
It happens every restart, our server restart every 2 hours, and it stucks. We need to clear the inventory data of players saved by this plugin to get the thing work properly. Not really able to understand why exactly that is happening. If you stop, and start the server, the issue remains the same.

**Comment by TechnicallyCoded** [comment]
Can you try removing the plugin and do the same thing that made it hang?

**Comment by NotSharwan** [comment]
The plugin has already been removed, and no issues or hangs have been observed since then.

**Comment by TechnicallyCoded** [comment]
Very peculiar... As you know, thousands of people use the plugin and this is the first report of this type I have seen. Unfortunate to say, but I think that this is one of the situations where something in your setup just doesn't line up with my code in some odd way and I have no idea what to do about it nor what to recommend be changed on your end :/

**Comment by TechnicallyCoded** [comment]
Do you have a testing server that you can replicate this issue on? Or was only that one server?

**Comment by TechnicallyCoded** [comment]
No additional information?

**Comment by NotSharwan** [comment]
Please accept my apologies for the delayed response! We've had the plugin removed for a while now and haven't had any disabling issues. When we add it again, it disables everything after a while and stops at `[InventoryRollbackPlus] Disabling InventoryRollbackPlus v1.6.5`. I'm not sure what's going on here. Also, I can't replicate on the test server because the shutdown issue occurs suddenly after using the plugin for about 2-3 days. If we delete the backup data for the save inventories, it will work properly on the next restart.

**Comment by TechnicallyCoded** [comment]
"it disables everything after a while"
1. I really would like to get the FULL server logs on this one. 
2. What is shutting down the server? It makes no sense as to why the server would just stop... 
3. What server host are you using?

If you don't want to provide your entire server logs to the public I can understand that, so I can add you on discord if you prefer providing your discord tag.

**Comment by NotSharwan** [comment]
Yes, when the server reboots. It begins disabling all plugins and hangs until it reaches the message `[InventoryRollbackPlus] Disabling InventoryRollbackPlus v1.6.5`.
1. In the report, I already mentioned the log - https://mcpaste.io/56217a3969641bab
2. The shutting down triggers at scheduled restarts, it saves the gave and starts disabling the plugins.
3. https://pebblehost.com/

I'm not sure why this disabling occurs, but it causes the server to hang and requires a staff member to manually restart it from the panel. The only solution we found was to temporarily disable the plugin, which solved the problem; we apologise for the inconvenience.
My discord tag:  `Shxrwan#0001`
