### ISSUE TITLE
Can you add a function for Auto Force Backup?

### ISSUE THREAD

**Issue by SaranWSM** [TechnicallyCoded/Inventory-Rollback-Plus#65]
Can you add a function for Auto Force Backup?

**Comment by TechnicallyCoded** [comment]
This is a duplicate of #11 , please comment there if there anything you want to add, or even just to show your support for the feature request! :D

**Comment by SaranWSM** [comment]
i need Auto Force Backup.

**Comment by TechnicallyCoded** [comment]
Go to issue #11
