### ISSUE TITLE
Bug report: Improper Shutdown of Async Tasks during Restarts

### ISSUE THREAD

**Issue by hemanth4121** [TechnicallyCoded/Inventory-Rollback-Plus#67]
### Bug description:
Console spams an error log about 'Nag author: 'TechnicallyCoded' of 'InventoryRollbackPlus' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.'

### Server details:
 - Server type & version: **[20:41:40 INFO]: Current: git-Purpur-1533 (MC: 1.18.1)**
 - InventoryRollbackPlus version: **Running InventoryRollbackPlus v1.6.5**

### How to reproduce:
Shut down the server/Restart it, to see the error.

### What was expected:
*The error shouldn't be there.

### Screenshots, logs & other:
https://pastebin.com/9ZrJHZQJ

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
Resolved in 1.6.7
