### ISSUE TITLE
Add pufferfish compatibility. (Unable to access playerdata from the server)

### ISSUE THREAD

**Issue by xxdemiigod** [TechnicallyCoded/Inventory-Rollback-Plus#70]
### Bug description:
*Whenever I use /irp restore <user> on the server, it will bring up the backup data menu. But I can't access any of the data itself to restore someone's items.*

### Server details:
 - Server type & version: *Pufferfish version git-Pufferfish-43 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1b5273f on HEAD)*
 - InventoryRollbackPlus version: *v1.6.4*

### How to reproduce:
*Log on. Use command /irp restore xxdemiigod (just my username for example), and try to select any of the backup data files (ie. deaths, joins, etc).*

### What was expected:
*The menu I'm used to seeing should pop up. The one with all of the chests labeled with the time and date in GMT.*

### Screenshots, logs & other:
(Sadly it's difficult to screenshot nothing happening)

#### **Additional info:**
*I have no idea if this is a bug with IRP or if a config or plugin is interfering with it. For context, we've had the server running for over a year now, and we reset once roughly every six months. This is our third reset, and since we switched hosting platforms, we had to put some heavy lag assist in place before we could upgrade. It was working fine until then. I think LagAssist might be interfering with something (or maybe not), but I don't know what I would be looking for in the server.yml. Really I'm just going everywhere for answers because Google isn't helping me and our server owner is very busy.*

**Comment by TechnicallyCoded** [comment]
Were permissions correctly assigned to the players? (See spigot page for exact permissions)
Could you provide a full server log file? (I can accept the logs through discord if you don't want to send them here)

**Comment by xxdemiigod** [comment]
I believe so. I have the admin role (*) and I tried adding the inventoryrollbackplus.* permission to that role manually. But it still didn't work.

[latest.log](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/files/8045518/latest.log)
Does that work? I'm new at learning this stuff. The error message that comes up isn't too far from the start-up of the server. Since I joined shortly after the reboot.

**Comment by TechnicallyCoded** [comment]
Ok, I think I know what is going on. However, I don't have a magic fix for you without updating the plugin. The server software you are running (Pufferfish) is modifying the names of the 'methods' such that they don't match what is to be expected from popular server versions like paper.

**Comment by xxdemiigod** [comment]
Darn alright. I'll update it as well, but thank you for letting me know about Pufferfish.

**Comment by TechnicallyCoded** [comment]
Just 1.18 update, everything else should be fine

**Comment by xxdemiigod** [comment]
Thank you! Would you like to close this now? Or do you want to keep it open for the Pufferfish thing?

**Comment by TechnicallyCoded** [comment]
Depends, does it work on pufferfish now that you are up to date?

**Comment by TechnicallyCoded** [comment]
Closed due to inactivity
