### ISSUE TITLE
Bug report: Cant hide tab completion

### ISSUE THREAD

**Issue by ArZorMC** [TechnicallyCoded/Inventory-Rollback-Plus#81]
### Bug description:
*I have a plugin which effectively block most plugins tab completion, even though I specifically block /irl and all sub commands it is still a tab completion option for players *

### Server details:
 - Paper version git-Paper-216 (MC: 1.18.1)
 - InventoryRollbackPlus v1.6.6

### How to reproduce:
Install Pl-Hide
Add the following to a group with mode blacklist:
      - irp
      - 'irp'
      - 'irp restore'
      - 'irp forcebackup'
      - 'irp enable'
      - 'irp disable'
      - 'irp reload'
      - 'irp help '
      - 'irp version'
### What was expected:
Tab completion to not show irp as an option

### Screenshots, logs & other:
https://gyazo.com/39e8ec75bb83eee12b8c8ca8d356ce4d

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
Fixed in commit dbcd4e323e689eff5b000ba1db2d3c9bd7e5a474

**Comment by TechnicallyCoded** [comment]
Resolved in 1.6.7
