### ISSUE TITLE
There's no backup made after EssentialsX /kill command

### ISSUE THREAD

**Issue by oskarkk** [TechnicallyCoded/Inventory-Rollback-Plus#85]
### Bug description:
No backup is made after killing a player with Essentials' `/kill` command. The normal vanilla Minecraft command triggers a backup.

### Server details:
 - Server type & version: Paper #242 1.18.2
 - InventoryRollbackPlus version: 1.6.6
 - EssentialsX: 2.19.4

### How to reproduce:
Use `/kill` command from Essentials on someone and then `/ir restore`.

### What was expected:
Every death triggering a backup, even caused by some plugin.

**Comment by TechnicallyCoded** [comment]
Essentials needs to use the right methods. Killing a player must also call a damage event prior to such event. Unfortunately, I won't fix this.

**Comment by oskarkk** [comment]
Are you sure that's the case? I don't know much Java, but it looks to me like Essentials is calling that event:

```
        final EntityDamageEvent ede = new EntityDamageEvent(matchPlayer, sender.isPlayer() && sender.getPlayer().getName().equals(matchPlayer.getName()) ? EntityDamageEvent.DamageCause.SUICIDE : EntityDamageEvent.DamageCause.CUSTOM, Float.MAX_VALUE);
        server.getPluginManager().callEvent(ede);
        if (ede.isCancelled() && sender.isPlayer() && !ess.getUser(sender.getPlayer()).isAuthorized("essentials.kill.force")) {
            return;
        }
        ede.getEntity().setLastDamageCause(ede);
        matchPlayer.setHealth(0);
```

From [com/earth2me/essentials/commands/Commandkill.java](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/commands/Commandkill.java)

If they really got that wrong, then I'll make an issue in Essentials' repo.

**Comment by TechnicallyCoded** [comment]
Hmm, I'll take a longer look at this, but if the entity damage event is triggered that's what the plugin listens to.

**Comment by TechnicallyCoded** [comment]
Just tested using essentials, it works here

**Comment by oskarkk** [comment]
I've just tested it again and it works, I've also tested killing another player (that's when it didn't work for me) and it also works. Maybe it's some weird bug that doesn't happen all the time. I'll keep an eye on it and I'll sometimes check if it works, but for now thank you and sorry for wasting your time.
