### ISSUE TITLE
Bug report: Players fail to join server running IRP

### ISSUE THREAD

**Issue by NiamiTV** [TechnicallyCoded/Inventory-Rollback-Plus#87]
### Bug description:
Players timeout while trying to join server with IRP

### Server details:
 - Server type & version: paper 1.18.2-267
 - InventoryRollbackPlus version: 1.6.6
 - EssentialsX version: 2.20.0-dev+3-c4f10d9

#### **Additional info:**
No extra console errors are shown, just that the user has timed out while trying to join and sometimes there is no join attempt shown in the log and the user just fails to connect. Removing IRP immediately stops these failed join attempts

**Comment by TechnicallyCoded** [comment]
Logs?

**Comment by NiamiTV** [comment]
https://pastebin.com/b21EQHp4

**Comment by NiamiTV** [comment]
There was never a join/login log message and that person told me they got an error at this time when they tried to join

**Comment by TechnicallyCoded** [comment]
Well I need logs to help you sorry

**Comment by TechnicallyCoded** [comment]
Issue will be closed in a day if no additional info is provided

**Comment by NiamiTV** [comment]
I have nothing else to add as no extra info was shown in the logs
