### ISSUE TITLE
Clock settings

### ISSUE THREAD

**Issue by MayorFluffy** [TechnicallyCoded/Inventory-Rollback-Plus#9]
Hey! 

```
## Set how the time is displayed on the backups.
time-zone: 'CET'
time-format: 'dd/MM/yyyy hh:mm:ss a z'
```

Is it possible to change the format of the time to a 24 hour clock? So to remove AM and PM, and make the time go up to 23:59 hour?

Im very happy about the plugin, and using it in a large server in the Netherlands. Here we don't use AM and PM and more than half the people don't even understand AM and PM. So it would be really nice if this option is possible, or can be created in the next patch.

**Comment by TechnicallyCoded** [comment]
This is already possible ^^. Here are the variables:

    y – Year (1996; 96)
    M – Month in year (July; Jul; 07)
    d – Day in month (1-31)
    E – Day name in week (Friday, Sunday)
    a – AM/PM marker (AM, PM)
    H – Hour in day (0-23)
    h – Hour in AM/PM (1-12)
    m – Minute in hour (0-60)
    s – Second in minute (0-60)
    z – Locale (GMT, Europe/Paris, ....)

PS: I think it's awesome you enjoy the plugin. However I check issues once a while manually and fixed the issue where I wasn't getting emails about new issues recently. Please private message me to get my attention next time... :/

PS 2: You left 4 stars, which is very nice, thank you. Is there anything that I can add to make that 5 xD?

**Comment by MayorFluffy** [comment]
Thank you!!! Idea to mention those placeholders in the plugin somehwere? Or on the web page?

Did 4 stars, because there is always place for improvement :) Almost never give 5 stars
