### ISSUE TITLE
Support: Only deaths are saving

### ISSUE THREAD

**Issue by mizsty** [TechnicallyCoded/Inventory-Rollback-Plus#91]
Hello,

My inventories upon death are saved however 'joins', 'quits', and 'world changes' will show that there is saved data, but the data won't display.

It just comes up as empty.

![2022-04-14_13 39 41](https://user-images.githubusercontent.com/103044064/163392320-1b1f164d-9e95-4b09-ad26-d4c7c8f37731.png)

![2022-04-14_13 36 55](https://user-images.githubusercontent.com/103044064/163392169-623ccc13-3af9-4fdf-a86c-ad65c5b3bcb8.png)

**Comment by TechnicallyCoded** [comment]
Logs please

**Comment by TechnicallyCoded** [comment]
Lack of reply
