### ISSUE TITLE
Bug report: Console Warning, but everything works well

### ISSUE THREAD

**Issue by iOshawott** [TechnicallyCoded/Inventory-Rollback-Plus#94]
### Bug description:
*A clear and concise description of what the bug is.*
So, when in config I type GMT+2. I'm getting
`[21:39:05 WARN]: [InventoryRollbackPlus] Time zone "GMT+2" in config.yml is invalid. Defaulting to "UTC"`
but everything works well and time zone is changed.

### Server details:
 - Server type & version: [21:41:25 INFO]: Current: git-Purpur-1563 (MC: 1.18.1)*
 - InventoryRollbackPlus version: Running InventoryRollbackPlus v1.6.6

### How to reproduce:
*Steps to reproduce the behavior. If not applicable just replace this line with N/A*
`time-zone: 'GMT+2'`
in config

### What was expected:
*A clear description of what you expected to happen. If not applicable just replace this line with N/A*
No error / warn is expected

**Comment by TechnicallyCoded** [comment]
Should be fixed in [345ff09](https://github.com/TechnicallyCoded/Inventory-Rollback-Plus/commit/345ff0921ab0bf91e66cf48d2871f6c929bb0799)
