### ISSUE TITLE
Bug report: Ir restore player gives access to every backup

### ISSUE THREAD

**Issue by TechRoot** [TechnicallyCoded/Inventory-Rollback-Plus#96]
### Bug description:
Clicking on head slot on /ir restore player gives access to every backup of every player ever joined.

### Server details:
[20:29:35 INFO]: This server is running Paper version git-Paper-333 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 9fd870d)
  Running InventoryRollbackPlus v1.6.6

### How to reproduce:
Give permission inventoryrollback.restore and inventoryrollback.viewbackups to a player, then let him use /ir restore ItsOwnName
Click on first slot, head slot,
a full list will be shown. Accessing every player backup.

### What was expected:
A player should only be able to access its own backups, not other ones.

**Comment by TechnicallyCoded** [comment]
Intended behavior. This is a moderation tool.
