### ISSUE TITLE
Bug report: messages.yml resets itself after reloading

### ISSUE THREAD

**Issue by kpAjun** [TechnicallyCoded/Inventory-Rollback-Plus#99]
### Bug description:
I replaced the default messages.yml with my own translated file, but every time I use /irp reload or restart the server, the files gets covered by the default messages again.

### Server details:
 - Paper 1.18.1
 - InventoryRollbackPlus version: 1.6.7

### How to reproduce:
Replace the messages.yml file with a modified one in the plugin folder and enter /irp reload or restart the server.

### What was expected:
The messages in the plugin's GUI should change.

### Screenshots, logs & other:
Nothing wrong in the logs, it just says that the plugin is being enabled.

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
![image](https://user-images.githubusercontent.com/29813490/179749589-af1efcef-e508-4af4-b140-e85bf893c652.png)
I just edited my messages file by adding many sssssss and it's clearly working

Maybe send me your translated file using a service like pastebin and I can take a look at it..?

**Comment by kpAjun** [comment]
Hello, I have tested it a few time and found out that the problem is with Chinese characters. If the file contains Chinese characters, it gets reset to default.
I used UTF-8 encoding. Is there a problem with it?
Thank you very much.

**Comment by kpAjun** [comment]
Hello, thank you for your help.
It was revealed that one of the messages contained a ' in it and caused the problem.
Sorry for occupying your time.
